name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 5 * * 0"   # domingos, 05:00 UTC (02:00 BRT)
  workflow_dispatch:      # botão de execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"
          UTC_OFFSET: -3
          AUTO_PUSH: true
          THEME: "radical"
